"use client";

import { useEffect, useId, useRef, useState } from "react";
import { THAI_BUDDHIST_LOCALE, THAI_TIME_ZONE } from "@/lib/thai-date";

const weekDays=["จ","อ","พ","พฤ","ศ","ส","อา"];
const months=["มกราคม","กุมภาพันธ์","มีนาคม","เมษายน","พฤษภาคม","มิถุนายน","กรกฎาคม","สิงหาคม","กันยายน","ตุลาคม","พฤศจิกายน","ธันวาคม"];
const iso=(date:Date)=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`;
const fromIso=(value:string)=>{const [year,month,day]=value.split("-").map(Number);return new Date(year,month-1,day,12);};

export function BuddhistDateInput({name,defaultValue="",required=false,maxToday=false,minValue,disabledWeekends=false,markedValue,id}:{name:string;defaultValue?:string;required?:boolean;maxToday?:boolean;minValue?:string;disabledWeekends?:boolean;markedValue?:string;id?:string}){
  const generatedId=useId();const inputId=id||generatedId;const root=useRef<HTMLDivElement>(null);const[selected,setSelected]=useState(defaultValue);const[open,setOpen]=useState(false);const[view,setView]=useState(()=>defaultValue?fromIso(defaultValue):new Date());
  useEffect(()=>{const form=root.current?.closest("form");const reset=()=>{setSelected(defaultValue);setView(defaultValue?fromIso(defaultValue):new Date());setOpen(false);};form?.addEventListener("reset",reset);return()=>form?.removeEventListener("reset",reset);},[defaultValue]);
  useEffect(()=>{function close(event:MouseEvent){if(!root.current?.contains(event.target as Node))setOpen(false);}function escape(event:KeyboardEvent){if(event.key==="Escape")setOpen(false);}document.addEventListener("mousedown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("mousedown",close);document.removeEventListener("keydown",escape);};},[]);
  const first=new Date(view.getFullYear(),view.getMonth(),1,12);const offset=(first.getDay()+6)%7;const days=Array.from({length:42},(_,index)=>new Date(view.getFullYear(),view.getMonth(),index-offset+1,12));const today=iso(new Date());const currentYear=new Date().getFullYear();const years=Array.from({length:121},(_,index)=>currentYear-index);
  function choose(date:Date){const value=iso(date);const weekend=date.getDay()===0||date.getDay()===6;if((maxToday&&value>today)||(minValue&&value<minValue)||(disabledWeekends&&weekend))return;setSelected(value);setView(date);setOpen(false);}
  const display=selected?new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{day:"2-digit",month:"2-digit",year:"numeric",timeZone:THAI_TIME_ZONE}).format(fromIso(selected)):"วว/ดด/ปปปป";
  return <div className="buddhist-date" ref={root} data-required={required||undefined}><input type="hidden" name={name} value={selected}/><button id={inputId} type="button" className="buddhist-date-trigger" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><span className={selected?"":"placeholder"}>{display}</span><span aria-hidden="true">▣</span></button>{open&&<div className="buddhist-calendar" role="dialog" aria-label="เลือกวันที่ พ.ศ."><header><label><span>เดือน</span><select aria-label="เลือกเดือน" value={view.getMonth()} onChange={event=>setView(current=>new Date(current.getFullYear(),Number(event.target.value),1,12))}>{months.map((month,index)=><option key={month} value={index}>{month}</option>)}</select></label><label><span>ปี พ.ศ.</span><select aria-label="เลือกปี พ.ศ." value={view.getFullYear()} onChange={event=>setView(current=>new Date(Number(event.target.value),current.getMonth(),1,12))}>{years.map(year=><option key={year} value={year}>{year+543}</option>)}</select></label></header><div className="calendar-weekdays">{weekDays.map(day=><span key={day}>{day}</span>)}</div><div className="calendar-days">{days.map(date=>{const value=iso(date);const outside=date.getMonth()!==view.getMonth();const weekend=date.getDay()===0||date.getDay()===6;const disabled=(maxToday&&value>today)||(Boolean(minValue)&&value<minValue!)||(disabledWeekends&&weekend);return <button type="button" key={value} className={`${outside?"outside ":""}${value===markedValue?"original ":""}${selected===value?"selected":""}`} disabled={disabled} aria-label={`${new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{dateStyle:"long"}).format(date)}${value===markedValue?" วันนัดเดิม":""}`} onClick={()=>choose(date)}>{date.getDate()}</button>;})}</div>{markedValue&&<div className="calendar-legend"><span><i className="available"/>เลือกได้</span><span><i className="unavailable"/>เลือกไม่ได้</span><span><i className="original"/>วันนัดเดิม</span><span><i className="chosen"/>วันที่เลือกใหม่</span></div>}<footer><button type="button" onClick={()=>setSelected("")}>ล้าง</button><button type="button" onClick={()=>{const now=new Date();if(!maxToday||iso(now)<=today)choose(now);}}>วันนี้</button></footer></div>}</div>;
}
