"use client";
import Image from "next/image";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import QRCode from "qrcode";
import generatePromptPayPayload from "promptpay-qr";
import { THAI_BUDDHIST_LOCALE, THAI_TIME_ZONE } from "@/lib/thai-date";

export type PaymentItem={id:string;paidAt:string;referenceCode:string;receiptNumber:string|null;description:string;amountSatang:number;method:string;status:string;receivedSatang:number|null;changeSatang:number|null;slipFileName:string|null};
const money=(satang:number)=>`฿${(satang/100).toLocaleString("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const paidAt=(value:string)=>new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{dateStyle:"medium",timeStyle:"short",timeZone:THAI_TIME_ZONE}).format(new Date(value));

export function PaymentForm({patientId,saving,onSaved,onError}:{patientId:string;saving:boolean;onSaved:()=>Promise<void>;onError:(message:string)=>void}){
  const[method,setMethod]=useState("เงินสด"),[amount,setAmount]=useState(""),[received,setReceived]=useState(""),[qr,setQr]=useState({payload:"",url:""});
  const promptPayId=process.env.NEXT_PUBLIC_PROMPTPAY_ID?.trim()||"";
  const qrPayload=useMemo(()=>{const value=Number(amount);if(method!=="โอนเงิน"||!Number.isFinite(value)||value<=0)return "";return promptPayId?generatePromptPayPayload(promptPayId,{amount:value}):`KUMED|TRANSFER|THB|${value.toFixed(2)}`;},[amount,method,promptPayId]);
  useEffect(()=>{let active=true;if(qrPayload)QRCode.toDataURL(qrPayload,{width:220,margin:1,color:{dark:"#123d32",light:"#ffffff"}}).then(url=>{if(active)setQr({payload:qrPayload,url});});return()=>{active=false;};},[qrPayload]);
  const amountNumber=Number(amount)||0,receivedNumber=Number(received)||0;
  const change=receivedNumber-amountNumber;
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();onError("");const body={...Object.fromEntries(new FormData(event.currentTarget)),kind:"payment",method,amount,receivedAmount:received,qrPayload};try{const response=await fetch(`/api/patients/${patientId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"บันทึกการชำระเงินไม่สำเร็จ");await onSaved();}catch(reason){onError(reason instanceof Error?reason.message:"บันทึกการชำระเงินไม่สำเร็จ");}}
  return <form className="record-form payment-form" data-payment-workflow="cash-v2" onSubmit={submit}><div className="field wide"><label>รายการ</label><input name="description" required/></div><div className="field"><label>{method==="เงินสด"?"จำนวนเงินที่ต้องชำระ (บาท)":"จำนวนเงิน (บาท)"}</label><input name="amount" value={amount} onChange={event=>setAmount(event.target.value)} type="number" min="0" step="0.01" required/></div><div className="field"><label>วิธีชำระเงิน</label><select name="method" value={method} onChange={event=>setMethod(event.target.value)}><option>เงินสด</option><option>โอนเงิน</option><option>สิทธิการรักษา</option></select></div>
    {method==="เงินสด"&&<><div className="field"><label>จำนวนเงินที่ได้รับ (บาท)</label><input name="receivedAmount" value={received} onChange={event=>setReceived(event.target.value)} type="number" min={amount||"0"} step="0.01" required/><small>จำนวนเงินที่ได้รับต้องไม่น้อยกว่าจำนวนเงินที่ต้องชำระ</small></div><div className={`cash-change ${change<0?"invalid":""}`}><span>เงินทอน<br/><small>เงินที่ได้รับ − เงินที่ต้องชำระ</small></span><strong>{money(Math.round(Math.max(0,change)*100))}</strong></div></>}
    {method==="สิทธิการรักษา"&&<div className="payment-note full"><strong>ใช้สิทธิการรักษา</strong><span>ระบบจะบันทึกรายการ ออกเลขใบเสร็จ และสร้างไฟล์ใบเสร็จให้อัตโนมัติ</span></div>}
    {method==="โอนเงิน"&&<div className="transfer-qr full">{qrPayload&&qr.payload===qrPayload?<Image unoptimized src={qr.url} width={180} height={180} alt={`QR Code ชำระเงิน ${amount} บาท`}/>:<div className="qr-placeholder">กรอกจำนวนเงินเพื่อสร้าง QR</div>}<div><strong>QR ชำระเงินแบบล็อกยอด</strong><span>ยอดชำระ {Number(amount)>0?money(Math.round(Number(amount)*100)):"–"}</span>{promptPayId?<small>สแกนชำระผ่านแอปธนาคาร แล้วแนบสลิปเพื่อยืนยัน</small>:<small className="form-error">ต้องกำหนด NEXT_PUBLIC_PROMPTPAY_ID เพื่อให้ QR ใช้ชำระผ่านธนาคารได้</small>}</div></div>}
    <div className="form-actions record-form-actions"><button className="primary-button" disabled={saving||method==="โอนเงิน"&&!qrPayload}>{saving?"กำลังบันทึก...":method==="โอนเงิน"?"สร้างรายการและรอสลิป":"บันทึกและออกใบเสร็จ"}</button></div></form>;
}

export function PaymentList({patientId,records,onChanged,onError}:{patientId:string;records:PaymentItem[];onChanged:()=>Promise<void>;onError:(message:string)=>void}){
  const[uploading,setUploading]=useState<string|null>(null);
  async function upload(paymentId:string,file:File|null){if(!file)return;setUploading(paymentId);onError("");const form=new FormData();form.set("slip",file);try{const response=await fetch(`/api/patients/${patientId}/payments/${paymentId}/slip`,{method:"POST",body:form});const result=await response.json();if(!response.ok)throw new Error(result.error||"อัปโหลดสลิปไม่สำเร็จ");await onChanged();}catch(reason){onError(reason instanceof Error?reason.message:"อัปโหลดสลิปไม่สำเร็จ");}finally{setUploading(null);}}
  if(!records.length)return <div className="record-empty"><strong>ยังไม่มีข้อมูลการชำระเงิน</strong><span>กด “เพิ่มรายการ” เพื่อบันทึกการชำระเงิน</span></div>;
  return <div className="payment-list">{records.map(item=><article className="payment-card" key={item.id}><div className="payment-main"><div><time>{paidAt(item.paidAt)}</time><h3>{item.description}</h3><p>{item.receiptNumber||item.referenceCode} · {item.method}</p>{item.method==="เงินสด"&&<small>ต้องชำระ {money(item.amountSatang)} · รับมา {money(item.receivedSatang||0)} · เงินทอน {money(item.changeSatang||0)}</small>}</div><div><strong>{money(item.amountSatang)}</strong><span className={item.status==="paid"?"payment-status paid":"payment-status pending"}>{item.status==="paid"?"ชำระแล้ว":"รอยืนยันสลิป"}</span></div></div><div className="payment-actions"><a className="primary-button receipt-print-button" href={`/api/patients/${patientId}/payments/${item.id}/receipt`} target="_blank" rel="noreferrer">พิมพ์ใบเสร็จ</a>{item.slipFileName?<a className="secondary-button" href={`/api/patients/${patientId}/payments/${item.id}/slip`} target="_blank" rel="noreferrer">ดูสลิป</a>:<label className="secondary-button slip-upload">{uploading===item.id?"กำลังอัปโหลด...":"＋ เพิ่มสลิป"}<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" disabled={uploading===item.id} onChange={event=>upload(item.id,event.target.files?.[0]||null)}/></label>}</div></article>)}</div>;
}
