"use client";
import { useState, type FormEvent } from "react";

export function RegistrationForm() {
  const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setNotice(""); setError(""); const form = event.currentTarget;
    try { const response = await fetch("/api/patients", { method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(Object.fromEntries(new FormData(form))) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || "ไม่สามารถบันทึกข้อมูลได้"); setNotice(`บันทึกเวชระเบียนของ ${result.patient.firstName} ${result.patient.lastName} เรียบร้อยแล้ว`); form.reset(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "ไม่สามารถบันทึกข้อมูลได้"); } finally { setSaving(false); }
  }
  return <section className="clinical-page"><header className="clinical-header"><div><h1>เพิ่มข้อมูลนิสิตและลงทะเบียนเวชระเบียนใหม่</h1><p>กรอกข้อมูลระบุตัวตน ตรวจสอบสิทธิการรักษาพยาบาล พร้อมบันทึกข้อมูลเพื่อเปิดแฟ้มประวัติสุขภาพ</p></div><button type="button" className="secondary-button" onClick={() => setNotice("เครื่องอ่านบัตรยังไม่เชื่อมต่อ")}>อ่านข้อมูลจากเครื่องอ่านบัตร</button></header>
    <form onSubmit={submit}><section className="clinical-card clinical-section"><h2 className="clinical-section-title">ข้อมูลระบุตัวตนและสถานภาพนิสิต</h2><div className="field-grid">
      <div className="field"><label htmlFor="citizen">เลขประจำตัวประชาชน (13 หลัก) <span className="required">*</span></label><input id="citizen" name="citizenId" inputMode="numeric" pattern="[0-9-]{13,17}" required /></div>
      <div className="field"><label htmlFor="student">รหัสนิสิต <span className="required">*</span></label><input id="student" name="studentId" required /></div>
      <div className="field"><label htmlFor="status">สถานภาพ</label><select id="status" name="status" defaultValue="นิสิตปัจจุบัน"><option>นิสิตปัจจุบัน</option><option>บุคลากร</option></select></div>
      <div className="field"><label htmlFor="title">คำนำหน้านาม <span className="required">*</span></label><select id="title" name="title" defaultValue="นางสาว" required><option>นางสาว</option><option>นาย</option><option>นาง</option></select></div>
      <div className="field"><label htmlFor="first">ชื่อจริง <span className="required">*</span></label><input id="first" name="firstName" required /></div><div className="field"><label htmlFor="last">นามสกุล <span className="required">*</span></label><input id="last" name="lastName" required /></div>
      <div className="field"><label htmlFor="birth">วัน/เดือน/ปีเกิด <span className="required">*</span></label><input id="birth" name="birthDate" type="date" required /></div><div className="field"><label htmlFor="gender">เพศ <span className="required">*</span></label><select id="gender" name="gender"><option>หญิง</option><option>ชาย</option><option>อื่น ๆ</option></select></div><div className="field"><label htmlFor="blood">หมู่เลือด</label><select id="blood" name="bloodGroup"><option value="">ไม่ระบุ</option><option>A Rh Positive (+)</option><option>B</option><option>O</option><option>AB</option></select></div>
      <div className="field wide"><label htmlFor="faculty">สังกัดคณะ <span className="required">*</span></label><select id="faculty" name="faculty" required><option>คณะเภสัชศาสตร์</option><option>คณะศิลปศาสตร์และวิทยาศาสตร์</option><option>คณะเกษตร กำแพงแสน</option></select></div><div className="field"><label htmlFor="major">ภาควิชา / สาขาวิชา <span className="required">*</span></label><input id="major" name="major" required /></div><div className="field"><label htmlFor="year">ชั้นปี <span className="required">*</span></label><select id="year" name="studyYear"><option>ปี 1</option><option>ปี 2</option><option>ปี 3</option><option>ปี 4</option></select></div>
      <div className="field wide"><label htmlFor="phone">เบอร์โทรศัพท์ <span className="required">*</span></label><input id="phone" name="phone" type="tel" required /></div><div className="field wide"><label htmlFor="email">อีเมล <span className="required">*</span></label><input id="email" name="email" type="email" required /></div>
      <div className="field wide"><label htmlFor="home-address">ที่อยู่ตามทะเบียนบ้าน</label><textarea id="home-address" name="homeAddress" /></div><div className="field wide"><label htmlFor="current-address">ที่พักปัจจุบัน</label><textarea id="current-address" name="currentAddress" /></div><div className="field full"><label htmlFor="allergies">ประวัติแพ้ยา / ข้อควรระวัง</label><textarea id="allergies" name="allergyNotes" /></div>
    </div></section><section className="clinical-card clinical-section"><h2 className="clinical-section-title">สิทธิการรักษาพยาบาลและประกันสุขภาพ</h2><div className="field-grid"><div className="field wide"><label htmlFor="coverage">สิทธิการรักษาพยาบาล</label><select id="coverage" name="coverage"><option>สิทธิกองทุนนิสิต</option><option>บัตรทอง</option><option>ประกันสังคม</option><option>ชำระเงินเอง</option></select></div><div className="field wide"><label htmlFor="coverage-status">สถานะภาพ</label><select id="coverage-status" name="coverageStatus"><option>ใช้งานได้</option><option>รอตรวจสอบ</option></select></div></div></section>
    {notice && <p className="form-notice" role="status">{notice}</p>}{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button type="reset" className="secondary-button" onClick={() => { setNotice(""); setError(""); }}>ล้างข้อมูล</button><button className="primary-button" type="submit" disabled={saving}>{saving ? "กำลังบันทึก..." : "บันทึกข้อมูล"}</button></div></form>
  </section>;
}
