"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { BuddhistDateInput } from "@/components/buddhist-date-input";
import { SensitiveInput } from "@/components/sensitive-input";
import { KPS_FACULTIES } from "@/lib/faculties";

type StudentData={studentId:string;citizenId:string;title:string;firstName:string;lastName:string;birthDate:string;gender:string;bloodGroup:string;faculty:string;major:string;studyYear:string;phone:string;email:string;homeAddress:string;currentAddress:string;status:string};
const titles=["นางสาว","นาย","นาง"],statuses=["นิสิตปัจจุบัน","บุคลากร"],genders=["หญิง","ชาย","อื่น ๆ"],bloodGroups=["A Rh Positive (+)","B","O","AB"],faculties=[...KPS_FACULTIES],years=["ปี 1","ปี 2","ปี 3","ปี 4"];
function Options({values,current,empty=false}:{values:string[];current?:string;empty?:boolean}){const items=current&&!values.includes(current)?[current,...values]:values;return <>{empty&&<option value="">ไม่ระบุ</option>}{items.map(value=><option key={value} value={value}>{value}</option>)}</>}

export function RegistrationForm(){
  const router=useRouter();const[lookupId,setLookupId]=useState("");const[student,setStudent]=useState<StudentData|null>(null);const[formVersion,setFormVersion]=useState(0);const[looking,setLooking]=useState(false);const[notice,setNotice]=useState("");const[error,setError]=useState("");const[saving,setSaving]=useState(false);
  async function lookup(event:FormEvent<HTMLFormElement>){event.preventDefault();const id=lookupId.trim();if(!id){setError("กรุณากรอกรหัสนิสิต");return;}setLooking(true);setNotice("");setError("");try{const response=await fetch(`/api/student-lookup/${encodeURIComponent(id)}`,{cache:"no-store"});const result=await response.json();if(!response.ok){if(result.patientId){setError(result.error);return;}throw new Error(result.error||"ไม่สามารถค้นหาข้อมูลนิสิตได้");}setStudent(result.student);setFormVersion(value=>value+1);setNotice(`${result.mock?"ข้อมูลจำลองสำหรับการนำเสนอ — ":""}ดึงข้อมูลของ ${result.student.title}${result.student.firstName} ${result.student.lastName} แล้ว กรุณาตรวจสอบก่อนบันทึก`);}catch(reason){setError(reason instanceof Error?reason.message:"ไม่สามารถค้นหาข้อมูลนิสิตได้");}finally{setLooking(false);}}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setNotice("");setError("");const form=event.currentTarget;try{const response=await fetch("/api/patients",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(form)))});const result=await response.json();if(!response.ok)throw new Error(result.error||"ไม่สามารถบันทึกข้อมูลได้");setNotice(`บันทึกเวชระเบียนของ ${result.patient.firstName} ${result.patient.lastName} เรียบร้อยแล้ว`);setStudent(null);setLookupId("");setFormVersion(value=>value+1);}catch(reason){setError(reason instanceof Error?reason.message:"ไม่สามารถบันทึกข้อมูลได้");}finally{setSaving(false);}}
  function clear(){setStudent(null);setLookupId("");setNotice("");setError("");setFormVersion(value=>value+1);}
  return <section className="clinical-page"><header className="clinical-header"><div><h1>ลงทะเบียนผู้ป่วยใหม่</h1><p>ค้นหาด้วยรหัสนิสิต ตรวจสอบข้อมูลที่ได้รับ แล้วบันทึกเพื่อเปิดแฟ้มประวัติสุขภาพ</p></div></header>
    <form className="student-lookup-card clinical-card" onSubmit={lookup}><div><label htmlFor="student-lookup">ค้นหาข้อมูลนิสิตจากระบบมหาวิทยาลัย</label><p>กรอกรหัสนิสิตเพื่อเติมข้อมูลส่วนบุคคลและข้อมูลการศึกษาโดยอัตโนมัติ</p></div><div className="student-lookup-control"><input id="student-lookup" value={lookupId} onChange={event=>{setLookupId(event.target.value);setError("");}} placeholder="กรอกรหัสนิสิต" autoComplete="off" required/><button className="primary-button" disabled={looking}>{looking?"กำลังค้นหา…":"ดึงข้อมูล"}</button></div><small>ข้อมูลจะถูกส่งผ่าน API ฝั่งเซิร์ฟเวอร์และไม่เก็บในระบบจนกว่าจะกด “บันทึกข้อมูล”</small></form>
    {notice&&<p className="form-notice" role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}{error.includes("ลงทะเบียนแล้ว")&&<button type="button" className="inline-link-button" onClick={()=>router.push(`/search?q=${encodeURIComponent(lookupId)}`)}>ค้นหาในระบบ</button>}</p>}
    <form key={formVersion} onSubmit={submit}><section className="clinical-card clinical-section"><h2 className="clinical-section-title">ข้อมูลระบุตัวตนและสถานภาพนิสิต</h2><div className="field-grid">
      <div className="field"><label htmlFor="citizen">เลขประจำตัวประชาชน (13 หลัก) <span className="required">*</span></label><SensitiveInput id="citizen" name="citizenId" kind="citizen" defaultValue={student?.citizenId||""} required/></div><div className="field"><label htmlFor="student">รหัสนิสิต <span className="required">*</span></label><input id="student" name="studentId" defaultValue={student?.studentId||""} required/></div><div className="field"><label htmlFor="status">สถานภาพ</label><select id="status" name="status" defaultValue={student?.status||"นิสิตปัจจุบัน"}><Options values={statuses} current={student?.status}/></select></div>
      <div className="field"><label htmlFor="title">คำนำหน้านาม <span className="required">*</span></label><select id="title" name="title" defaultValue={student?.title||"นางสาว"} required><Options values={titles} current={student?.title}/></select></div><div className="field"><label htmlFor="first">ชื่อจริง <span className="required">*</span></label><input id="first" name="firstName" defaultValue={student?.firstName||""} required/></div><div className="field"><label htmlFor="last">นามสกุล <span className="required">*</span></label><input id="last" name="lastName" defaultValue={student?.lastName||""} required/></div>
      <div className="field"><label htmlFor="birth">วัน/เดือน/ปีเกิด <span className="required">*</span></label><BuddhistDateInput id="birth" name="birthDate" defaultValue={student?.birthDate||""} required maxToday/></div><div className="field"><label htmlFor="gender">เพศ <span className="required">*</span></label><select id="gender" name="gender" defaultValue={student?.gender||"หญิง"}><Options values={genders} current={student?.gender}/></select></div><div className="field"><label htmlFor="blood">หมู่เลือด</label><select id="blood" name="bloodGroup" defaultValue={student?.bloodGroup||""}><Options values={bloodGroups} current={student?.bloodGroup} empty/></select></div>
      <div className="field wide"><label htmlFor="faculty">สังกัดคณะ <span className="required">*</span></label><select id="faculty" name="faculty" defaultValue={student?.faculty||faculties[0]} required><Options values={faculties} current={student?.faculty}/></select></div><div className="field"><label htmlFor="major">ภาควิชา / สาขาวิชา <span className="required">*</span></label><input id="major" name="major" defaultValue={student?.major||""} required/></div><div className="field"><label htmlFor="year">ชั้นปี <span className="required">*</span></label><select id="year" name="studyYear" defaultValue={student?.studyYear||years[0]}><Options values={years} current={student?.studyYear}/></select></div>
      <div className="field wide"><label htmlFor="phone">เบอร์โทรศัพท์ <span className="required">*</span></label><SensitiveInput id="phone" name="phone" kind="phone" defaultValue={student?.phone||""} required/></div><div className="field wide"><label htmlFor="email">อีเมล <span className="required">*</span></label><input id="email" name="email" type="email" defaultValue={student?.email||""} required/></div>
      <div className="field wide"><label htmlFor="home-address">ที่อยู่ตามทะเบียนบ้าน</label><textarea id="home-address" name="homeAddress" defaultValue={student?.homeAddress||""}/></div><div className="field wide"><label htmlFor="current-address">ที่พักปัจจุบัน</label><textarea id="current-address" name="currentAddress" defaultValue={student?.currentAddress||""}/></div><div className="field full"><label htmlFor="allergies">ประวัติแพ้ยา / ข้อควรระวัง</label><textarea id="allergies" name="allergyNotes"/></div>
    </div></section><section className="clinical-card clinical-section"><h2 className="clinical-section-title">สิทธิการรักษาพยาบาลและประกันสุขภาพ</h2><div className="field-grid"><div className="field wide"><label htmlFor="coverage">สิทธิการรักษาพยาบาล</label><select id="coverage" name="coverage"><option>สิทธิกองทุนนิสิต</option><option>บัตรทอง</option><option>ประกันสังคม</option><option>ชำระเงินเอง</option></select></div><div className="field wide"><label htmlFor="coverage-status">สถานะภาพ</label><select id="coverage-status" name="coverageStatus"><option>ใช้งานได้</option><option>รอตรวจสอบ</option></select></div></div></section>
    <div className="form-actions"><button type="button" className="secondary-button" onClick={clear}>ล้างข้อมูล</button><button className="primary-button" type="submit" disabled={saving}>{saving?"กำลังบันทึก...":"บันทึกข้อมูล"}</button></div></form>
  </section>;
}
