"use client";

import { useEffect, useMemo, useState } from "react";
import { THAI_BUDDHIST_LOCALE, THAI_TIME_ZONE } from "@/lib/thai-date";

type RankedItem={label:string;value:number};
type ReportData={range:{start:string;end:string};summary:{patientCount:number;visitCount:number;appointmentCount:number;paidAmountSatang:number};dailyVisits:RankedItem[];departments:RankedItem[];visitTypes:RankedItem[];diagnoses:RankedItem[];paymentMethods:RankedItem[]};
const periods=[{value:"month",label:"เดือนปัจจุบัน"},{value:"three-months",label:"3 เดือนล่าสุด"},{value:"academic-year",label:"ปีการศึกษาปัจจุบัน"},{value:"year",label:"ปีปัจจุบัน"}];
const money=new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",minimumFractionDigits:2});
const number=new Intl.NumberFormat("th-TH");
const shortDate=(value:string)=>new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{day:"numeric",month:"short",timeZone:THAI_TIME_ZONE}).format(new Date(`${value}T12:00:00+07:00`));
const longDate=(value:string)=>new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{day:"numeric",month:"short",year:"numeric",timeZone:THAI_TIME_ZONE}).format(new Date(value));
const dateTime=(value:string)=>new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{dateStyle:"long",timeStyle:"short",timeZone:THAI_TIME_ZONE}).format(new Date(value));
const safeCell=(value:string|number)=>{const text=String(value);return /^[=+\-@]/.test(text)?`'${text}`:text;};
const escapeHtml=(value:string|number)=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]!);
function reportRows(data:ReportData){return [["รายงานสรุปผลการให้บริการ KU-MED"],["สถานพยาบาลมหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตกำแพงแสน"],["ช่วงเวลา",`${longDate(data.range.start)} - ${longDate(data.range.end)}`],[],["ข้อมูลสรุป","จำนวน"],["ผู้ป่วยในระบบ",data.summary.patientCount],["การเข้ารับบริการ",data.summary.visitCount],["การนัดหมาย",data.summary.appointmentCount],["ยอดชำระแล้ว (บาท)",(data.summary.paidAmountSatang/100).toFixed(2)],[],["ห้องตรวจ / แผนก","จำนวนครั้ง"],...data.departments.map(item=>[item.label,item.value]),[],["ประเภทการเข้ารับบริการ","จำนวนครั้ง"],...data.visitTypes.map(item=>[item.label,item.value]),[],["การวินิจฉัยที่พบบ่อย","จำนวนครั้ง"],...data.diagnoses.map(item=>[item.label,item.value]),[],["ช่องทางการชำระเงิน","จำนวนรายการ"],...data.paymentMethods.map(item=>[item.label,item.value])] as (string|number)[][];}
function download(content:string,type:string,fileName:string){const url=URL.createObjectURL(new Blob([content],{type}));const link=document.createElement("a");link.href=url;link.download=fileName;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}

export function ReportsPanel(){
  const[period,setPeriod]=useState("month");const[data,setData]=useState<ReportData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[reload,setReload]=useState(0);const[issuedAt,setIssuedAt]=useState(()=>new Date().toISOString());
  useEffect(()=>{const controller=new AbortController();fetch(`/api/reports?period=${period}`,{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"โหลดรายงานไม่สำเร็จ");setData(result);setIssuedAt(new Date().toISOString());}).catch(reason=>{if(reason.name!=="AbortError")setError(reason instanceof Error?reason.message:"โหลดรายงานไม่สำเร็จ");}).finally(()=>setLoading(false));return()=>controller.abort();},[period,reload]);
  const peak=useMemo(()=>Math.max(1,...(data?.dailyVisits.map(item=>item.value)||[])),[data]);
  function exportCsv(){if(!data)return;const csv="\uFEFF"+reportRows(data).map(row=>row.map(cell=>`"${safeCell(cell).replaceAll('"','""')}"`).join(",")).join("\r\n");download(csv,"text/csv;charset=utf-8",`KU-MED-report-${period}.csv`);}
  function exportExcel(){if(!data)return;const rows=reportRows(data).map(row=>`<tr>${row.map((cell,index)=>`<${index===0?"th":"td"}>${escapeHtml(cell)}</${index===0?"th":"td"}>`).join("")}</tr>`).join("");const html=`\uFEFF<!doctype html><html lang="th"><head><meta charset="utf-8"><style>body{font-family:Tahoma,sans-serif}h1{text-align:center;color:#075f46}table{border-collapse:collapse;width:100%}th,td{border:1px solid #9ca3af;padding:8px;text-align:left}th{background:#e9f7f1}</style></head><body><h1>รายงานสรุปผลการให้บริการ KU-MED</h1><table>${rows}</table></body></html>`;download(html,"application/vnd.ms-excel;charset=utf-8",`KU-MED-report-${period}.xls`);}
  return <section className="clinical-page reports-page"><header className="clinical-header report-page-header"><div><h1>รายงาน</h1><p>ภาพรวมข้อมูลการให้บริการจากฐานข้อมูลสถานพยาบาล</p></div><div className="report-toolbar"><label><span>ช่วงเวลา</span><select value={period} onChange={event=>{setLoading(true);setError("");setPeriod(event.target.value);}}>{periods.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><div className="report-export-actions"><button type="button" className="primary-button" disabled={!data} onClick={()=>window.print()}>พิมพ์ / PDF</button><button type="button" className="secondary-button" disabled={!data} onClick={exportExcel}>Excel</button><button type="button" className="secondary-button" disabled={!data} onClick={exportCsv}>CSV</button></div></div></header>
    {error&&<div className="report-error" role="alert"><strong>ไม่สามารถแสดงรายงานได้</strong><span>{error}</span><button type="button" onClick={()=>{setLoading(true);setError("");setReload(value=>value+1);}}>ลองใหม่</button></div>}
    {loading&&!data?<ReportSkeleton/>:data&&<><div className="report-summary-grid"><SummaryCard icon="👥" label="ผู้ป่วยในระบบ" value={number.format(data.summary.patientCount)} tone="mint"/><SummaryCard icon="✚" label="เข้ารับบริการ" value={number.format(data.summary.visitCount)} tone="green"/><SummaryCard icon="▣" label="การนัดหมาย" value={number.format(data.summary.appointmentCount)} tone="blue"/><SummaryCard icon="฿" label="ยอดชำระแล้ว" value={money.format(data.summary.paidAmountSatang/100)} tone="gold"/></div>
      <div className="report-dashboard-grid"><article className="clinical-card report-chart-card"><header><div><h2>ปริมาณผู้เข้ารับบริการ</h2><p>{longDate(data.range.start)} – {longDate(data.range.end)}</p></div><strong>{number.format(data.summary.visitCount)} <small>ครั้ง</small></strong></header><div className="visit-chart" aria-label="กราฟจำนวนผู้เข้ารับบริการรายวัน">{data.dailyVisits.length?data.dailyVisits.map(item=><div className="visit-bar-column" key={item.label}><span className="visit-bar-value">{item.value}</span><i style={{height:`${Math.max(8,item.value/peak*100)}%`}}/><small>{shortDate(item.label)}</small></div>):<Empty text="ยังไม่มีข้อมูลการเข้ารับบริการในช่วงนี้"/>}</div></article><article className="clinical-card report-breakdown-card"><header><h2>ห้องตรวจ / แผนก</h2><p>สัดส่วนการให้บริการ</p></header><RankedBars items={data.departments} total={data.summary.visitCount}/></article></div>
      <div className="report-lower-grid"><article className="clinical-card report-list-card"><header><h2>ประเภทการเข้ารับบริการ</h2><span>จำนวนครั้ง</span></header><RankedRows items={data.visitTypes}/></article><article className="clinical-card report-list-card"><header><h2>การวินิจฉัยที่พบบ่อย</h2><span>5 อันดับแรก</span></header><RankedRows items={data.diagnoses}/></article><article className="clinical-card report-list-card"><header><h2>ช่องทางการชำระเงิน</h2><span>จำนวนรายการ</span></header><RankedRows items={data.paymentMethods}/></article></div><OfficialReport data={data} period={periods.find(item=>item.value===period)?.label||""} issuedAt={issuedAt}/></>}
  </section>;
}
function SummaryCard({icon,label,value,tone}:{icon:string;label:string;value:string;tone:string}){return <article className="clinical-card report-summary-card"><span className={`summary-icon ${tone}`}>{icon}</span><div><p>{label}</p><strong>{value}</strong></div></article>}
function RankedBars({items,total}:{items:RankedItem[];total:number}){return <div className="ranked-bars">{items.length?items.slice(0,5).map((item,index)=><div key={item.label}><div><span>{item.label}</span><strong>{number.format(item.value)} ครั้ง</strong></div><i><b style={{width:`${Math.max(4,item.value/Math.max(1,total)*100)}%`}} className={`bar-tone-${index}`}/></i></div>):<Empty text="ยังไม่มีข้อมูล"/>}</div>}
function RankedRows({items}:{items:RankedItem[]}){return <div className="ranked-rows">{items.length?items.slice(0,5).map((item,index)=><div key={item.label}><span className="rank-number">{index+1}</span><p title={item.label}>{item.label}</p><strong>{number.format(item.value)}</strong></div>):<Empty text="ยังไม่มีข้อมูล"/>}</div>}
function Empty({text}:{text:string}){return <p className="report-empty">{text}</p>}
function ReportSkeleton(){return <><div className="report-summary-grid">{[1,2,3,4].map(item=><div className="clinical-card report-skeleton summary" key={item}/>)}</div><div className="clinical-card report-skeleton chart"/></>}
function OfficialTable({title,items,unit="ครั้ง"}:{title:string;items:RankedItem[];unit?:string}){return <section className="official-report-section"><h2>{title}</h2><table><thead><tr><th>ลำดับ</th><th>รายการ</th><th>จำนวน</th></tr></thead><tbody>{items.length?items.map((item,index)=><tr key={item.label}><td>{index+1}</td><td>{item.label}</td><td>{number.format(item.value)} {unit}</td></tr>):<tr><td colSpan={3}>ไม่มีข้อมูล</td></tr>}</tbody></table></section>}
function OfficialReport({data,period,issuedAt}:{data:ReportData;period:string;issuedAt:string}){return <article className="official-report-print"><header><div className="official-report-mark">KU</div><div><h1>รายงานสรุปผลการให้บริการ</h1><p>สถานพยาบาลมหาวิทยาลัยเกษตรศาสตร์ วิทยาเขตกำแพงแสน</p><small>เลขที่ 1 หมู่ 6 ตำบลกำแพงแสน อำเภอกำแพงแสน จังหวัดนครปฐม 73140</small></div></header><div className="official-report-meta"><p><strong>ประเภทรายงาน:</strong> {period}</p><p><strong>ช่วงข้อมูล:</strong> {longDate(data.range.start)} ถึง {longDate(data.range.end)}</p><p><strong>วันที่ออกรายงาน:</strong> {dateTime(issuedAt)} น.</p></div><section className="official-report-summary"><div><span>ผู้ป่วยในระบบ</span><strong>{number.format(data.summary.patientCount)}</strong><small>คน</small></div><div><span>เข้ารับบริการ</span><strong>{number.format(data.summary.visitCount)}</strong><small>ครั้ง</small></div><div><span>การนัดหมาย</span><strong>{number.format(data.summary.appointmentCount)}</strong><small>รายการ</small></div><div><span>ยอดชำระแล้ว</span><strong>{money.format(data.summary.paidAmountSatang/100)}</strong></div></section><div className="official-report-tables"><OfficialTable title="สรุปตามห้องตรวจ / แผนก" items={data.departments}/><OfficialTable title="สรุปตามประเภทการเข้ารับบริการ" items={data.visitTypes}/><OfficialTable title="การวินิจฉัยที่พบบ่อย" items={data.diagnoses}/><OfficialTable title="สรุปช่องทางการชำระเงิน" items={data.paymentMethods} unit="รายการ"/></div><footer><p>หมายเหตุ: รายงานนี้จัดทำจากข้อมูลที่บันทึกในระบบ KU-MED ตามช่วงเวลาที่ระบุ</p><div><span>ลงชื่อ ............................................................ ผู้จัดทำรายงาน</span><span>ลงชื่อ ............................................................ ผู้ตรวจสอบ</span></div></footer></article>}
