"use client";

import { useEffect, useMemo, useState } from "react";
import { THAI_BUDDHIST_LOCALE, THAI_TIME_ZONE } from "@/lib/thai-date";

type RankedItem={label:string;value:number};
type ReportData={range:{start:string;end:string};summary:{patientCount:number;visitCount:number;appointmentCount:number;paidAmountSatang:number};dailyVisits:RankedItem[];departments:RankedItem[];visitTypes:RankedItem[];diagnoses:RankedItem[];paymentMethods:RankedItem[]};
const periods=[{value:"month",label:"เดือนปัจจุบัน"},{value:"three-months",label:"3 เดือนล่าสุด"},{value:"academic-year",label:"ปีการศึกษาปัจจุบัน"},{value:"year",label:"ปีปัจจุบัน"}];
const money=new Intl.NumberFormat("th-TH",{style:"currency",currency:"THB",minimumFractionDigits:2});
const number=new Intl.NumberFormat("th-TH");
const shortDate=(value:string)=>new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{day:"numeric",month:"short",timeZone:THAI_TIME_ZONE}).format(new Date(`${value}T12:00:00+07:00`));
const longDate=(value:string)=>new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{day:"numeric",month:"short",year:"numeric",timeZone:THAI_TIME_ZONE}).format(new Date(value));

export function ReportsPanel(){
  const[period,setPeriod]=useState("month");const[data,setData]=useState<ReportData|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[reload,setReload]=useState(0);
  useEffect(()=>{const controller=new AbortController();fetch(`/api/reports?period=${period}`,{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error||"โหลดรายงานไม่สำเร็จ");setData(result);}).catch(reason=>{if(reason.name!=="AbortError")setError(reason instanceof Error?reason.message:"โหลดรายงานไม่สำเร็จ");}).finally(()=>setLoading(false));return()=>controller.abort();},[period,reload]);
  const peak=useMemo(()=>Math.max(1,...(data?.dailyVisits.map(item=>item.value)||[])),[data]);
  function exportCsv(){if(!data)return;const rows:(string|number)[][]=[["รายงาน KU-MED"],["ช่วงเวลา",`${longDate(data.range.start)} - ${longDate(data.range.end)}`],[],["ตัวชี้วัด","จำนวน"],["ผู้ป่วยทั้งหมด",data.summary.patientCount],["เข้ารับบริการ",data.summary.visitCount],["นัดหมาย",data.summary.appointmentCount],["รายรับ (บาท)",(data.summary.paidAmountSatang/100).toFixed(2)],[],["วันที่","ผู้เข้ารับบริการ"],...data.dailyVisits.map(item=>[item.label,item.value])];const csv="\uFEFF"+rows.map(row=>row.map(cell=>`"${String(cell??"").replaceAll('"','""')}"`).join(",")).join("\r\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));link.download=`KU-MED-report-${period}.csv`;link.click();URL.revokeObjectURL(link.href);}
  return <section className="clinical-page reports-page"><header className="clinical-header report-page-header"><div><h1>รายงาน</h1><p>ภาพรวมข้อมูลการให้บริการจากฐานข้อมูลสถานพยาบาล</p></div><div className="report-toolbar"><label><span>ช่วงเวลา</span><select value={period} onChange={event=>{setLoading(true);setError("");setPeriod(event.target.value);}}>{periods.map(item=><option key={item.value} value={item.value}>{item.label}</option>)}</select></label><button type="button" className="secondary-button" disabled={!data} onClick={exportCsv}>ดาวน์โหลด CSV</button></div></header>
    {error&&<div className="report-error" role="alert"><strong>ไม่สามารถแสดงรายงานได้</strong><span>{error}</span><button type="button" onClick={()=>{setLoading(true);setError("");setReload(value=>value+1);}}>ลองใหม่</button></div>}
    {loading&&!data?<ReportSkeleton/>:data&&<><div className="report-summary-grid"><SummaryCard icon="👥" label="ผู้ป่วยในระบบ" value={number.format(data.summary.patientCount)} tone="mint"/><SummaryCard icon="✚" label="เข้ารับบริการ" value={number.format(data.summary.visitCount)} tone="green"/><SummaryCard icon="▣" label="การนัดหมาย" value={number.format(data.summary.appointmentCount)} tone="blue"/><SummaryCard icon="฿" label="ยอดชำระแล้ว" value={money.format(data.summary.paidAmountSatang/100)} tone="gold"/></div>
      <div className="report-dashboard-grid"><article className="clinical-card report-chart-card"><header><div><h2>ปริมาณผู้เข้ารับบริการ</h2><p>{longDate(data.range.start)} – {longDate(data.range.end)}</p></div><strong>{number.format(data.summary.visitCount)} <small>ครั้ง</small></strong></header><div className="visit-chart" aria-label="กราฟจำนวนผู้เข้ารับบริการรายวัน">{data.dailyVisits.length?data.dailyVisits.map(item=><div className="visit-bar-column" key={item.label}><span className="visit-bar-value">{item.value}</span><i style={{height:`${Math.max(8,item.value/peak*100)}%`}}/><small>{shortDate(item.label)}</small></div>):<Empty text="ยังไม่มีข้อมูลการเข้ารับบริการในช่วงนี้"/>}</div></article><article className="clinical-card report-breakdown-card"><header><h2>ห้องตรวจ / แผนก</h2><p>สัดส่วนการให้บริการ</p></header><RankedBars items={data.departments} total={data.summary.visitCount}/></article></div>
      <div className="report-lower-grid"><article className="clinical-card report-list-card"><header><h2>ประเภทการเข้ารับบริการ</h2><span>จำนวนครั้ง</span></header><RankedRows items={data.visitTypes}/></article><article className="clinical-card report-list-card"><header><h2>การวินิจฉัยที่พบบ่อย</h2><span>5 อันดับแรก</span></header><RankedRows items={data.diagnoses}/></article><article className="clinical-card report-list-card"><header><h2>ช่องทางการชำระเงิน</h2><span>จำนวนรายการ</span></header><RankedRows items={data.paymentMethods}/></article></div></>}
  </section>;
}
function SummaryCard({icon,label,value,tone}:{icon:string;label:string;value:string;tone:string}){return <article className="clinical-card report-summary-card"><span className={`summary-icon ${tone}`}>{icon}</span><div><p>{label}</p><strong>{value}</strong></div></article>}
function RankedBars({items,total}:{items:RankedItem[];total:number}){return <div className="ranked-bars">{items.length?items.slice(0,5).map((item,index)=><div key={item.label}><div><span>{item.label}</span><strong>{number.format(item.value)} ครั้ง</strong></div><i><b style={{width:`${Math.max(4,item.value/Math.max(1,total)*100)}%`}} className={`bar-tone-${index}`}/></i></div>):<Empty text="ยังไม่มีข้อมูล"/>}</div>}
function RankedRows({items}:{items:RankedItem[]}){return <div className="ranked-rows">{items.length?items.slice(0,5).map((item,index)=><div key={item.label}><span className="rank-number">{index+1}</span><p title={item.label}>{item.label}</p><strong>{number.format(item.value)}</strong></div>):<Empty text="ยังไม่มีข้อมูล"/>}</div>}
function Empty({text}:{text:string}){return <p className="report-empty">{text}</p>}
function ReportSkeleton(){return <><div className="report-summary-grid">{[1,2,3,4].map(item=><div className="clinical-card report-skeleton summary" key={item}/>)}</div><div className="clinical-card report-skeleton chart"/></>}
