"use client";

import { useState, type FormEvent } from "react";
import { BuddhistDateInput } from "@/components/buddhist-date-input";
import { addBusinessDays } from "@/lib/business-date";
import { THAI_TIME_ZONE } from "@/lib/thai-date";

type AppointmentData={id:string;scheduledAt:string;endsAt:string|null;department:string;clinician:string|null;reason:string};
const dateInBangkok=(value:string)=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",timeZone:THAI_TIME_ZONE}).format(new Date(value));
const times=Array.from({length:13},(_,index)=>{const minutes=9*60+index*30;return `${String(Math.floor(minutes/60)).padStart(2,"0")}:${String(minutes%60).padStart(2,"0")}`;});

export function RescheduleAppointmentButton({patientId,appointment}:{patientId:string;appointment:AppointmentData}){
  const[open,setOpen]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
  const originalDate=dateInBangkok(appointment.scheduledAt);const earliestDate=addBusinessDays(originalDate,-3);const suggestedDate=addBusinessDays(originalDate,1);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");try{const response=await fetch(`/api/patients/${patientId}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(new FormData(event.currentTarget)),kind:"appointment",appointmentId:appointment.id})});const result=await response.json();if(!response.ok)throw new Error(result.error||"เลื่อนนัดไม่สำเร็จ");window.location.reload();}catch(reason){setError(reason instanceof Error?reason.message:"เลื่อนนัดไม่สำเร็จ");setSaving(false);}}
  return <><button type="button" className="secondary-button" onClick={()=>setOpen(true)}>เลื่อนนัด</button>{open&&<div className="record-modal-backdrop" role="presentation" onMouseDown={()=>setOpen(false)}><section className="record-modal reschedule-modal" role="dialog" aria-modal="true" aria-labelledby="reschedule-title" onMouseDown={event=>event.stopPropagation()}><header><div><h2 id="reschedule-title">เลื่อนวันและเวลานัดหมาย</h2><p>ข้อมูลผู้ป่วยและรายละเอียดการนัดหมายจะคงเดิม</p></div><button type="button" className="modal-close-button" aria-label="ปิดหน้าต่าง" onClick={()=>setOpen(false)}><span aria-hidden="true">×</span></button></header><div className="reschedule-fixed-data"><div><span>รายการนัด</span><strong>{appointment.reason}</strong></div><div><span>แผนก</span><strong>{appointment.department}</strong></div><div><span>แพทย์ / ผู้ให้บริการ</span><strong>{appointment.clinician||"รอระบุ"}</strong></div></div><form className="record-form" onSubmit={submit}><div className="field"><label>วันนัดหมายใหม่</label><BuddhistDateInput name="scheduledDate" defaultValue={suggestedDate} minValue={earliestDate} markedValue={originalDate} disabledWeekends required/></div><div className="field"><label>เวลานัดหมายใหม่</label><select name="scheduledTime" defaultValue="09:00" required>{times.map(time=><option key={time} value={time}>{time} น.</option>)}</select></div><p className="reschedule-rule">เลือกได้เฉพาะวันจันทร์–ศุกร์ เวลา 09:00–15:00 น. หากเลื่อนให้เร็วขึ้น เลื่อนได้ไม่เกิน 3 วันทำการจากวันนัดเดิม</p>{error&&<p className="form-error record-form-actions" role="alert">{error}</p>}<div className="form-actions record-form-actions"><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>ยกเลิก</button><button className="primary-button" disabled={saving}>{saving?"กำลังบันทึก...":"ยืนยันการเลื่อนนัด"}</button></div></form></section></div>}</>;
}
