"use client";
import { useEffect, useState, type FormEvent } from "react";

type Settings = { displayName:string; role:string; email:string; phone:string; notifyAnnouncements:boolean; notifyMonthlyReports:boolean; notifySecurity:boolean };
const defaults: Settings = { displayName:"สุพิตตา ชัยงาม", role:"ผู้ดูแลระบบ", email:"supitta@ku.ac.th", phone:"081-234-5678", notifyAnnouncements:true, notifyMonthlyReports:true, notifySecurity:true };

export function SettingsForm() {
  const [settings,setSettings]=useState(defaults); const [notice,setNotice]=useState(""); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
  useEffect(()=>{let active=true;fetch("/api/settings").then(async response=>{if(!response.ok)throw new Error();return response.json();}).then(result=>{if(active&&result.settings)setSettings(result.settings);}).catch(()=>{if(active)setError("ยังโหลดการตั้งค่าจากฐานข้อมูลไม่ได้ ระบบแสดงค่าเริ่มต้น");});return()=>{active=false;};},[]);
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setNotice("");setError("");const form=event.currentTarget;const data=new FormData(form);const payload={displayName:data.get("displayName"),email:data.get("email"),phone:data.get("phone"),notifyAnnouncements:data.has("notifyAnnouncements"),notifyMonthlyReports:data.has("notifyMonthlyReports"),notifySecurity:data.has("notifySecurity")};try{const response=await fetch("/api/settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error||"ไม่สามารถบันทึกการตั้งค่าได้");setSettings(result.settings);setNotice("บันทึกการตั้งค่าเรียบร้อยแล้ว");}catch(reason){setError(reason instanceof Error?reason.message:"ไม่สามารถบันทึกการตั้งค่าได้");}finally{setSaving(false);}}
  return <section className="clinical-page"><header className="clinical-header"><div><h1>การตั้งค่า</h1><p>จัดการข้อมูลบัญชี ความปลอดภัย และการแจ้งเตือนของระบบ</p></div></header><form onSubmit={submit}><div className="settings-columns"><section className="clinical-card clinical-section"><h2 className="clinical-section-title">ข้อมูลส่วนตัว</h2><div className="field-grid"><div className="field wide"><label htmlFor="display-name">ชื่อ–นามสกุล</label><input id="display-name" name="displayName" value={settings.displayName} onChange={e=>setSettings({...settings,displayName:e.target.value})}/></div><div className="field wide"><label htmlFor="role">ตำแหน่ง</label><input id="role" value={settings.role} readOnly /></div><div className="field wide"><label htmlFor="settings-email">อีเมล</label><input id="settings-email" name="email" type="email" value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></div><div className="field wide"><label htmlFor="settings-phone">หมายเลขโทรศัพท์</label><input id="settings-phone" name="phone" type="tel" value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})}/></div></div></section>
    <div><section className="clinical-card settings-note"><h2>ความปลอดภัย</h2><p>การเปลี่ยนรหัสผ่านจะเปิดใช้พร้อมระบบยืนยันตัวตนจริง</p><button type="button" className="secondary-button" onClick={()=>setNotice("ระบบเปลี่ยนรหัสผ่านยังไม่เชื่อมต่อ")}>เปลี่ยนรหัสผ่าน</button></section><section className="clinical-card settings-note"><h2>การแจ้งเตือน</h2><p>เลือกข่าวสารที่ต้องการรับจาก KU-MED</p><div className="toggle-list"><label className="toggle-row"><span>ประกาศของสถานพยาบาล</span><input name="notifyAnnouncements" type="checkbox" checked={settings.notifyAnnouncements} onChange={e=>setSettings({...settings,notifyAnnouncements:e.target.checked})}/></label><label className="toggle-row"><span>รายงานประจำเดือน</span><input name="notifyMonthlyReports" type="checkbox" checked={settings.notifyMonthlyReports} onChange={e=>setSettings({...settings,notifyMonthlyReports:e.target.checked})}/></label><label className="toggle-row"><span>แจ้งเตือนความปลอดภัย</span><input name="notifySecurity" type="checkbox" checked={settings.notifySecurity} onChange={e=>setSettings({...settings,notifySecurity:e.target.checked})}/></label></div></section></div></div>
    {notice&&<p className="form-notice" role="status">{notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="primary-button" type="submit" disabled={saving}>{saving?"กำลังบันทึก...":"บันทึกการเปลี่ยนแปลง"}</button></div></form></section>;
}
