"use client";

import { useState, type FormEvent } from "react";
import { ICD10_ENTRIES } from "@/lib/icd10";
import { MedicalCertificate } from "@/components/medical-certificate";
import { THAI_BUDDHIST_LOCALE, THAI_TIME_ZONE } from "@/lib/thai-date";

type RecordData={id:string;visitedAt:string;department:string;diagnosis:string;clinician:string|null;paymentType:string|null;visitType:string;visitNumber:string|null;temperature:number|null;bloodPressure:string|null;pulse:number|null;oxygenSaturation:number|null;weightKg:number|null;heightCm:number|null;chiefComplaint:string|null;diagnosisCode:string|null;diagnosisName:string|null;treatmentPlan:string|null;medicationOrders:string|null};
type PatientData={id:string;title:string;firstName:string;lastName:string;citizenId:string;studentId:string;birthDate:string;phone:string};

const formatDateTime=(value:string)=>new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{dateStyle:"long",timeStyle:"short",timeZone:THAI_TIME_ZONE}).format(new Date(value));
const localDateTime=(value:string)=>new Intl.DateTimeFormat("sv-SE",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:THAI_TIME_ZONE}).format(new Date(value)).replace(" ","T");

export function TreatmentRecordActions({patient,record}:{patient:PatientData;record:RecordData}){
  const[mode,setMode]=useState<"edit"|"summary"|"certificate"|null>(null);const[saving,setSaving]=useState(false);const[error,setError]=useState("");
  async function update(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const body={...Object.fromEntries(new FormData(event.currentTarget)),recordId:record.id};try{const response=await fetch(`/api/patients/${patient.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||"แก้ไขข้อมูลไม่สำเร็จ");window.location.reload();}catch(reason){setError(reason instanceof Error?reason.message:"แก้ไขข้อมูลไม่สำเร็จ");setSaving(false);}}
  async function remove(){if(!window.confirm("ยืนยันการลบประวัติการรักษารายการนี้? ข้อมูลที่ลบจะไม่สามารถกู้คืนได้"))return;setSaving(true);setError("");try{const response=await fetch(`/api/patients/${patient.id}`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({recordId:record.id})});const result=await response.json();if(!response.ok)throw new Error(result.error||"ลบข้อมูลไม่สำเร็จ");window.location.reload();}catch(reason){setError(reason instanceof Error?reason.message:"ลบข้อมูลไม่สำเร็จ");setSaving(false);}}
  function printCertificate(){setMode("certificate");}
  return <><footer className="treatment-actions"><span>✓ บันทึกเวชระเบียนโดย {record.clinician||"ผู้ให้บริการ"}</span><div><button type="button" onClick={()=>setMode("edit")}>แก้ไขบันทึก</button><button type="button" onClick={remove} disabled={saving} className="danger-action">ลบข้อมูล</button><button type="button" onClick={printCertificate}>พิมพ์ใบรับรองแพทย์</button><button type="button" className="summary-action" onClick={()=>setMode("summary")}>ดูสรุปเวชระเบียนเต็ม</button></div></footer>{error&&<p className="form-error" role="alert">{error}</p>}
    {mode==="edit"&&<div className="record-modal-backdrop" role="presentation" onMouseDown={()=>setMode(null)}><section className="record-modal" role="dialog" aria-modal="true" aria-labelledby="edit-record-title" onMouseDown={event=>event.stopPropagation()}><header><h2 id="edit-record-title">แก้ไขประวัติการรักษา</h2><button type="button" onClick={()=>setMode(null)}>×</button></header><form className="record-form edit-record-form" onSubmit={update}><div className="field"><label>วันที่เข้ารับบริการ</label><input name="visitedAt" type="datetime-local" defaultValue={localDateTime(record.visitedAt)} required/></div><div className="field"><label>เลขที่รับบริการ (VN)</label><input name="visitNumber" defaultValue={record.visitNumber||""}/></div><div className="field"><label>ห้องตรวจ / แผนก</label><select name="department" defaultValue={record.department}><option>ห้องตรวจ1</option><option>ห้องตรวจ2</option><option>ห้องตรวจพิเศษ</option><option>ห้องตรวจ7 (ห้องหัตการ) ห้องสำหรับทำแผล</option></select></div><div className="field"><label>แพทย์ผู้ตรวจ</label><input name="clinician" defaultValue={record.clinician||""}/></div><div className="field"><label>ประเภทการรับบริการ</label><select name="visitType" defaultValue={record.visitType}><option>ตรวจรักษา</option><option>ติดตามผล</option><option>ฉุกเฉิน</option></select></div><div className="field"><label>รหัส ICD-10</label><select name="diagnosisCode" defaultValue={record.diagnosisCode||""}><option value="">ไม่ระบุ</option>{ICD10_ENTRIES.map(item=><option key={item.code} value={item.code}>{item.code} — {item.description}</option>)}</select></div><div className="field full"><label>อาการสำคัญ</label><textarea name="chiefComplaint" defaultValue={record.chiefComplaint||""}/></div><div className="field full"><label>หัตถการ / การดูแล</label><textarea name="treatmentPlan" defaultValue={record.treatmentPlan||""}/></div><div className="field full"><label>รายการยา</label><textarea name="medicationOrders" defaultValue={record.medicationOrders||""}/></div>{error&&<p className="form-error record-form-actions">{error}</p>}<div className="form-actions record-form-actions"><button type="button" className="secondary-button" onClick={()=>setMode(null)}>ยกเลิก</button><button className="primary-button" disabled={saving}>{saving?"กำลังบันทึก...":"บันทึกการแก้ไข"}</button></div></form></section></div>}
    {mode==="summary"&&<div className="record-modal-backdrop" role="presentation" onMouseDown={()=>setMode(null)}><section className="record-modal record-summary" role="dialog" aria-modal="true" aria-labelledby="record-summary-title" onMouseDown={event=>event.stopPropagation()}><header><div><h2 id="record-summary-title">สรุปเวชระเบียนเต็ม</h2><p>{patient.title}{patient.firstName} {patient.lastName} · {formatDateTime(record.visitedAt)}</p></div><button type="button" onClick={()=>setMode(null)}>×</button></header><dl><Summary label="VN" value={record.visitNumber}/><Summary label="ห้องตรวจ" value={record.department}/><Summary label="แพทย์" value={record.clinician}/><Summary label="สิทธิการรักษา" value={record.paymentType}/><Summary label="อาการสำคัญ" value={record.chiefComplaint}/><Summary label="การวินิจฉัย" value={`${record.diagnosisCode?`${record.diagnosisCode} — `:""}${record.diagnosisName||record.diagnosis}`}/><Summary label="หัตถการ / การดูแล" value={record.treatmentPlan}/><Summary label="รายการยา" value={record.medicationOrders}/><Summary label="สัญญาณชีพ" value={`BT ${record.temperature??"-"} °C · BP ${record.bloodPressure||"-"} · PR ${record.pulse??"-"} bpm · SpO₂ ${record.oxygenSaturation??"-"}%`}/></dl><div className="form-actions"><button className="primary-button" type="button" onClick={()=>window.print()}>พิมพ์สรุปเวชระเบียน</button></div></section></div>}
    {mode==="certificate"&&<MedicalCertificate patient={patient} record={record} onClose={()=>setMode(null)}/>}
  </>;
}

function Summary({label,value}:{label:string;value:string|null|undefined}){return <div><dt>{label}</dt><dd>{value||"ไม่ระบุ"}</dd></div>}
