import { NextRequest,NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { THAI_BUDDHIST_LOCALE,THAI_TIME_ZONE } from "@/lib/thai-date";

export const runtime="nodejs";
const escape=(value:string)=>value.replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]!));
const money=(satang:number|null)=>((satang||0)/100).toLocaleString("th-TH",{minimumFractionDigits:2,maximumFractionDigits:2});

export async function GET(_request:NextRequest,{params}:{params:Promise<{id:string;paymentId:string}>}){const{id,paymentId}=await params;const payment=await getDb().payment.findFirst({where:{id:paymentId,patientId:id},include:{patient:{select:{title:true,firstName:true,lastName:true,studentId:true}}}});if(!payment)return NextResponse.json({error:"ไม่พบใบเสร็จ"},{status:404});const date=new Intl.DateTimeFormat(THAI_BUDDHIST_LOCALE,{dateStyle:"long",timeStyle:"short",timeZone:THAI_TIME_ZONE}).format(payment.paidAt);const html=`<!doctype html><html lang="th"><head><meta charset="utf-8"><title>ใบเสร็จ ${escape(payment.receiptNumber||payment.referenceCode)}</title><style>body{font-family:Arial,sans-serif;color:#16372f;margin:0;background:#eef3f1}.receipt{box-sizing:border-box;width:80mm;min-height:120mm;margin:20px auto;padding:8mm;background:#fff;border-top:5px solid #08785e;box-shadow:0 10px 30px #0002}h1{font-size:18px;margin:0;color:#08785e}header p{font-size:11px;margin:3px 0}.number{margin:16px 0;padding:8px;background:#eff8f5;font-size:12px}dl{font-size:12px}dl div{display:flex;justify-content:space-between;gap:12px;padding:7px 0;border-bottom:1px dashed #ccd7d3}dd{margin:0;text-align:right}.total{font-size:17px;font-weight:bold}.status{margin-top:16px;text-align:center;color:#08785e;font-weight:bold}.actions{text-align:center;margin:16px}@media print{body{background:#fff}.receipt{margin:0;box-shadow:none}.actions{display:none}@page{size:80mm 120mm;margin:0}}</style></head><body><article class="receipt"><header><h1>สถานพยาบาลมหาวิทยาลัยเกษตรศาสตร์</h1><p>วิทยาเขตกำแพงแสน</p></header><div class="number">ใบเสร็จเลขที่ <b>${escape(payment.receiptNumber||payment.referenceCode)}</b><br>${escape(date)}</div><dl><div><dt>ผู้รับบริการ</dt><dd>${escape(`${payment.patient.title}${payment.patient.firstName} ${payment.patient.lastName}`)}<br>${escape(payment.patient.studentId)}</dd></div><div><dt>รายการ</dt><dd>${escape(payment.description)}</dd></div><div><dt>วิธีชำระ</dt><dd>${escape(payment.method)}</dd></div><div class="total"><dt>ยอดรวม</dt><dd>${money(payment.amountSatang)} บาท</dd></div>${payment.method==="เงินสด"?`<div><dt>รับเงิน</dt><dd>${money(payment.receivedSatang)} บาท</dd></div><div><dt>เงินทอน</dt><dd>${money(payment.changeSatang)} บาท</dd></div>`:""}</dl><p class="status">${payment.status==="paid"?"ชำระเงินเรียบร้อย":"รอการยืนยันการชำระเงิน"}</p></article><div class="actions"><button onclick="window.print()">พิมพ์ / บันทึกเป็น PDF</button></div></body></html>`;return new NextResponse(html,{headers:{"Content-Type":"text/html; charset=utf-8","Content-Disposition":`inline; filename="${payment.receiptNumber||payment.referenceCode}.html"`,"Cache-Control":"private, no-store"}});}
